// <auto-generated />
using System;
using Lombard.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lombard.DAL.Migrations
{
    [DbContext(typeof(EFDbContext))]
    partial class EFDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("Lombard.DAL.Models.Item", b =>
                {
                    b.Property<int?>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<decimal>("PurchasePrice");

                    b.Property<double>("Quantity");

                    b.Property<decimal>("SellingPrice");

                    b.Property<int?>("TransactionId");

                    b.Property<string>("Unit");

                    b.HasKey("ItemId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Items");

                    b.HasData(
                        new { ItemId = 1, Name = "Kubek", PurchasePrice = 100m, Quantity = 2.0, SellingPrice = 0m },
                        new { ItemId = 2, Name = "Kubek2", PurchasePrice = 100m, Quantity = 2.0, SellingPrice = 0m }
                    );
                });

            modelBuilder.Entity("Lombard.DAL.Models.Transaction", b =>
                {
                    b.Property<int?>("TransactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("TransactionDate");

                    b.Property<int>("TransactionType");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new { TransactionId = 1, TransactionDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), TransactionType = 0 }
                    );
                });

            modelBuilder.Entity("Lombard.DAL.Models.TransactionItem", b =>
                {
                    b.Property<int?>("TransactionItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ItemId");

                    b.Property<int>("TransactionId");

                    b.HasKey("TransactionItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionsItems");

                    b.HasData(
                        new { TransactionItemId = 1, ItemId = 2, TransactionId = 1 },
                        new { TransactionItemId = 2, ItemId = 1, TransactionId = 1 }
                    );
                });

            modelBuilder.Entity("Lombard.DAL.Models.Item", b =>
                {
                    b.HasOne("Lombard.DAL.Models.Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId");
                });

            modelBuilder.Entity("Lombard.DAL.Models.TransactionItem", b =>
                {
                    b.HasOne("Lombard.DAL.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lombard.DAL.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
